name:                wow-auction
version:             0.1.0.0
github:              "githubuser/wow-auction"
license:             BSD3
author:              "FH"
maintainer:          "morpheus.hu14@gmail.com"
copyright:           "2018 FH"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/wow-auction#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- http-conduit
- http-client-tls
- scientific
- vector

library:
  source-dirs: src

executables:
  wow-auction-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wow-auction

tests:
  wow-auction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wow-auction
